name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 0.1.6
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^0.4.3+1
  firebase_storage: ^3.1.0
  sqflite: ^1.1.6+5
  path: ^1.6.4
  path_provider: ^1.3.0
  transparent_image: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter